version: '3'
services:
  app1:
    container_name: app1
    build: ./app
    environment:
      - HOSTNAME="app1"
    ports:
      - 5000:5000
  
  app2:
    container_name: app2
    build: ./app
    environment:
      - HOSTNAME="app2"
    ports:
      - 5001:5000
  
  redis:
    container_name: redis-flask
    image: redis:7.4
