title: 我的笔记库
description: 技术学习与知识管理
url: "https://pomelo33.github.io"
baseurl: "/myknowledge"

# Jekyll 配置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/  # 按分类和标题生成永久链接

# 禁用不必要的文件处理
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

# 自定义集合：笔记
collections:
  notes:
    output: true
    permalink: /:collection/:path/

# 压缩 HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []

# 分页配置
paginate: 10
paginate_path: "/page:num/"

# 导航菜单配置
navigation:
  - title: 首页
    url: /
  - title: 分类
    url: /categories/
  - title: 标签
    url: /tags/
  - title: 搜索
    url: /search/
  - title: 关于
    url: /about/