title: "My Notes"
description: "My Notes"
theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme #
baseurl: "" 
url: "" 
markdown: kramdown

plugins:
  - jekyll-feed

exclude: [convert_notes.py, containerd, web, title_map.json]
