title: My Notes
description: Personal knowledge notes.
baseurl: ""
url: "https://pomelo33.github.io/myknowledge"

remote_theme: "jekyll/minima@1e8a445"

markdown: kramdown
paginate: 15
paginate_path: "/page:num/"

tag_page_layout: tag
tag_permalink_style: pretty

exclude: ["convert_notes.py"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-tagging