title: My Notes
description: My Notes
theme: just-the-docs

# GitHub Pages 必需
remote_theme: just-the-docs

# 搜索功能
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 5
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# 设置默认首页重定向
# landing_page:
#   redirect: /notes/
